---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: system/e2e
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-endpointgroupbinding
  failurePolicy: Fail
  name: validate-endpointgroupbinding.h3poteto.dev
  rules:
  - apiGroups:
    - operator.h3poteto.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - endpointgroupbindings
  sideEffects: None
