apiVersion: operator.h3poteto.dev/v1alpha1
kind: EndpointGroupBinding
metadata:
  name: h3poteto-test
  namespace: default
spec:
  endpointGroupArn: arn:aws:globalaccelerator::564677439943:accelerator/d113ae41-29df-496d-b8d2-316b322764bf/listener/f1fe2960/endpoint-group/eea4ad34cd00
  weight: 100
  serviceRef:
    name: h3poteto-test
