apiVersion: v1
kind: Service
metadata:
  annotations:
    h3poteto.dev/aws-global-accelerator-enabled: "yes"
  name: h3poteto-test
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 6443
  type: NodePort
  selector:
    app: h3poteto
